--CREATE DATABASE db_tuum;
DROP TABLE IF EXISTS TRANSACTIONS;
DROP TABLE IF EXISTS ACCOUNT_BALANCE;
DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT (
  ACCOUNT_ID VARCHAR(50) PRIMARY KEY ,
  CUSTOMER_ID VARCHAR(20) NOT NULL,
  COUNTRY VARCHAR(20) NOT NULL
);

CREATE TABLE ACCOUNT_BALANCE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ACCOUNT_ID VARCHAR(50) NOT NULL,
  CURRENCY_TYPE VARCHAR(5) NOT NULL ,
  BALANCE NUMERIC(12, 2) DEFAULT 0,
  FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

CREATE TABLE TRANSACTIONS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ACCOUNT_ID VARCHAR(50) NOT NULL,
  CURRENCY_TYPE VARCHAR(5) NOT NULL ,
  TRANSFER_AMOUNT NUMERIC(12, 2) DEFAULT 0,
  BALANCE NUMERIC(12, 2) DEFAULT 0,
  TRANSACTION_TYPE VARCHAR(5) NOT NULL ,
  TRANSACTION_DESC VARCHAR(100) NOT NULL ,
  TRANSACTION_DATETIME DATE NOT NULL,
  FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

INSERT INTO ACCOUNT(ACCOUNT_ID,CUSTOMER_ID,COUNTRY) VALUES ('123456','TestTuumCustomer','Estonia');
INSERT INTO ACCOUNT_BALANCE(ACCOUNT_ID, CURRENCY_TYPE, BALANCE) VALUES ('123456','EUR',100);
INSERT INTO TRANSACTIONS(ACCOUNT_ID,CURRENCY_TYPE,TRANSFER_AMOUNT,BALANCE,TRANSACTION_TYPE, TRANSACTION_DESC,TRANSACTION_DATETIME)
VALUES ('123456','EUR',20,20,'IN','Transfer credit 20 euro','2023-07-09');
INSERT INTO TRANSACTIONS(ACCOUNT_ID,CURRENCY_TYPE,TRANSFER_AMOUNT,BALANCE,TRANSACTION_TYPE, TRANSACTION_DESC,TRANSACTION_DATETIME)
VALUES ('123456','EUR',10,10,'OUT','Transfer debit 10 euro','2023-07-09');